# Generated by Django 4.1.3 on 2022-11-09 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_alter_autor_options_alter_autor_apellidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='descripcion',
        ),
    ]
