# Generated by Django 4.1.3 on 2022-11-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0007_remove_libro_autor_id_libro_autor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='descripcion',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='autor',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creación'),
        ),
        migrations.RemoveField(
            model_name='libro',
            name='autor_id',
        ),
        migrations.AddField(
            model_name='libro',
            name='autor_id',
            field=models.ManyToManyField(to='libro.autor'),
        ),
    ]
