# Generated by Django 4.1.3 on 2022-11-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0008_autor_descripcion_autor_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
